Fix error: cannot find module 'node:url'
Environment:
- node 14.17.3
- serverless framework 3.27.0 (local)
- plugin 12.0.4

Error:
Error: Cannot find module 'node:url'

Fix:
I changed require to import to make it work.